# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\'\n\x03Job\x12\x0e\n\x06\x64uties\x18\x01 \x03(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"*\n\x06Person\x12\x12\n\x04jobs\x18\x01 \x03(\x0b\x32\x04.Job\x12\x0c\n\x04name\x18\x02 \x01(\t\"*\n\x0eJobApplication\x12\x18\n\x10\x61pplication_date\x18\x01 \x01(\x03\"\x10\n\x0eVoidInvocation2a\n\x07\x43ompany\x12)\n\x05Ready\x12\x0f.VoidInvocation\x1a\x0f.VoidInvocation\x12+\n\x0fSendApplication\x12\x07.Person\x1a\x0f.JobApplicationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOB']._serialized_start=17
  _globals['_JOB']._serialized_end=56
  _globals['_PERSON']._serialized_start=58
  _globals['_PERSON']._serialized_end=100
  _globals['_JOBAPPLICATION']._serialized_start=102
  _globals['_JOBAPPLICATION']._serialized_end=144
  _globals['_VOIDINVOCATION']._serialized_start=146
  _globals['_VOIDINVOCATION']._serialized_end=162
  _globals['_COMPANY']._serialized_start=164
  _globals['_COMPANY']._serialized_end=261
# @@protoc_insertion_point(module_scope)
